### PR TITLE
Update the readme files examples

### PR DESCRIPTION
**Pull request by DoctorJohn**
The next release will contain some breaking changes. While we're working on it, I'll defer updating the readme file to hopefully prevent confusion potentially caused by the updated examples.

### CODE REVIEW

**Comment by kousu** [comment]
Oh cool. So are you planning to make `session` optional? And passed in explicitly? That's better than what I had in #4.

**Comment by DoctorJohn** [comment]
Yes, I figured it's more flexible this way. The aiogqlc could then stay minimal and focus on encapsulating the protocol.

Before I release these changes in a new major version, I at least want to add some basic tests. I'll work on that next weekend.

**Comment by kamadorueda** [comment]
I really like this change, hope to see it pushed forward!

Regarding documentation, pdoc3 is very simple and nice. I've used it successfully in two other projects:

```sh
#! /usr/bin/env bash

function main {
      echo '[INFO] Building' \
  &&  poetry run pdoc \
        --config 'git_link_template="https://github.com/kamadorueda/aioextensions/blob/latest/{path}#L{start_line}-L{end_line}"' \
        --config 'sort_identifiers=False' \
        --force \
        --html \
        --output-dir docs/ \
        aioextensions \
  &&  mv docs/aioextensions/* docs/ \

}

main
```
https://github.com/kamadorueda/aioextensions/blob/latest/build/docs.sh#L5

result:

https://kamadorueda.github.io/aioextensions/

**Comment by DoctorJohn** [comment]
Thanks for your interest and recommending pdoc3 @kamadorueda . I'll do some experimenting with it.

Regarding the changes: Unfortunately I haven't had time to write proper tests and docs yet. But nevertheless I'll merge this PR now and release a beta version.

**Pull request merged**
